# Generated by Django 6.1 on 2026-09-02 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область/регион')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('phones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон(ы)')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, help_text='Только цифры из первого номера в phones. Для мягкой сверки дублей на этапе тёплого звонка — без строгого unique.', max_length=32, null=True, verbose_name='Телефон (нормализованный)')),
                ('emails', models.CharField(blank=True, max_length=500, null=True, verbose_name='Email(ы)')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник данных')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Заметки / специфика компании')),
                ('preferred_channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Канал отправки предложения')),
                ('is_sent_by_manager', models.BooleanField(default=False, verbose_name='КП отправлено менеджером')),
                ('callback_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата авто-перезвона (+3 дня)')),
                ('stage', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('letter_sent', 'Ждет отправки письма / КП'), ('success', 'Партнёр'), ('refusal', 'Отказ'), ('invalid', 'Невалидный / Ошибка')], default='new', max_length=20, verbose_name='Статус воронки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_leads', to=settings.AUTH_USER_MODEL, verbose_name='Закреплен за оператором')),
                ('categories', models.ManyToManyField(blank=True, related_name='companies', to='leads.category', verbose_name='Виды деятельности')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='accounts.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Положительно (Ждет письмо/согласен)'), ('call_back', 'Перезвонить позже'), ('refusal', 'Отказ'), ('wrong_number', 'Неправильный номер / Нет связи')], max_length=30, verbose_name='Результат звонка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время звонка')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'История звонка',
                'verbose_name_plural': 'История звонков',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['team', 'stage'], name='leads_compa_team_id_ff4113_idx'),
        ),
    ]
