# Generated by Django 5.2.17 on 2026-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Должен совпадать с Company.source', max_length=255, unique=True, verbose_name='Ключ источника')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название (для удобства)')),
                ('is_released', models.BooleanField(default=False, verbose_name='Открыт для команды')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда открыли')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, help_text='Пусто = закрыт для всех. Добавь команду — она увидит лиды.', related_name='data_sources', to='accounts.team', verbose_name='Открыт для команд')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
                'ordering': ['-is_released', 'key'],
            },
        ),
    ]
