# Generated by Django 5.2.17 on 2026-09-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_datasource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['key'], 'verbose_name': 'Источник данных', 'verbose_name_plural': 'Источники данных'},
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='released_at',
        ),
    ]
