# Generated by Django 5.2.17 on 2026-09-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок слайду')),
                ('text', models.TextField(verbose_name='Текст слайду')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати')),
            ],
            options={
                'verbose_name': 'Слайд карусельки',
                'verbose_name_plural': 'Слайди карусельки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Наш центр', max_length=100, verbose_name='Назва центру (шапка/футер)')),
                ('hero_title', models.CharField(default='Ми поруч із тими, кому зараз найважче', max_length=200, verbose_name='Заголовок на головній')),
                ('hero_subtitle', models.TextField(blank=True, default='Коротко про центр: кому допомагаємо, як довго працюємо, чому це важливо.', verbose_name='Підзаголовок на головній')),
                ('footer_about', models.TextField(blank=True, default='Підтримуємо тих, хто найбільше потребує допомоги.', verbose_name='Короткий опис у футері')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='Посилання на TikTok')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Посилання на Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Посилання на Instagram')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
