# Generated by Django 6.1.1 on 2026-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_bot_token_and_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public_profile',
            field=models.BooleanField(default=False, help_text='Увімкни, щоб людина зʼявилась у блоці «Команда» на публічній сторінці', verbose_name='Показувати картку на сайті'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_order',
            field=models.PositiveIntegerField(default=0, help_text='Менше число — раніше в списку', verbose_name='Порядок на сайті'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_photo_url',
            field=models.URLField(blank=True, help_text='Пряме посилання на зображення. Порожньо — покаже кружечок з першою літерою імені', verbose_name='Фото (посилання)'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_role_title',
            field=models.CharField(blank=True, help_text='Людська назва ролі для відвідувачів сайту (наприклад «Куратор напрямку»), а не внутрішній код capability', max_length=100, verbose_name='Посада для сайту'),
        ),
    ]
