# Generated by Django 5.2.17 on 2026-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_public_profile_user_public_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_photo',
            field=models.ImageField(blank=True, help_text='Завантаж файл — це пріоритетний варіант. Якщо порожньо — покаже кружечок з першою літерою імені.', null=True, upload_to='staff/', verbose_name='Фото — файл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_photo_url',
            field=models.URLField(blank=True, help_text='Використовується, тільки якщо файл нижче не завантажено. Пряме посилання на зображення.', verbose_name='Фото — посилання (запасний варіант)'),
        ),
    ]
