# Generated by Django 6.1.1 on 2026-09-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_provider', models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI-compatible')], default='groq', max_length=20, verbose_name='Провайдер')),
                ('api_key', models.CharField(help_text='Ключ вида gsk_... для Groq', max_length=255, verbose_name='API Key')),
                ('api_base_url', models.CharField(default='https://api.groq.com/openai/v1', help_text='Для Groq оставь как есть. Для других — свой endpoint.', max_length=255, verbose_name='Base URL')),
                ('model_name', models.CharField(default='openai/gpt-oss-20b', help_text='Например: openai/gpt-oss-20b, qwen/qwen3.8-27b', max_length=100, verbose_name='Модель')),
                ('base_kp_text', models.TextField(blank=True, help_text='Полный эталонный текст обращения: описание организации, таблица потребностей, реквизиты и т.д. Модель будет адаптировать его под конкретного лида.', verbose_name='Базовый текст КП')),
                ('system_prompt', models.TextField(blank=True, default='Ти допомагаєш писати персоналізовані звернення про гуманітарну допомогу від ГО «Майбутнє-Нове Покоління Україна». Пиши українською мовою. Зберігай факти про підопічних і потреби. Не вигадуй реквізити.', help_text='Дополнительные инструкции модели. Можно оставить пустым.', verbose_name='Системный промпт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки AI',
                'verbose_name_plural': 'Настройки AI',
            },
        ),
    ]
